'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.33440
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Room_Rent.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property amex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("amex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [dbRent_blank]
        '''GO
        '''/****** Object:  Table [dbo].[tblWorkers]    Script Date: 07/17/2014 19:24:43 ******/
        '''/****** Object:  Table [dbo].[tblVouchers]    Script Date: 07/17/2014 19:24:43 ******/
        '''/****** Object:  Table [dbo].[tblStock]    Script Date: 07/17/2014 19:24:43 ******/
        '''/****** Object:  Table [dbo].[tblShiftFee]    Script Date: 07/17/2014 19:24:43 ******/
        '''/****** Object:  Table [dbo].[tblSettings2]    Script Date: 07/17/2014 19:24:43 ******/
        '''/****** Object:  Table [dbo].[tblSettings]    Scrip [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Data_s() As String
            Get
                Return ResourceManager.GetString("Data_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property eftpos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eftpos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property mastercard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mastercard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property other_card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("other_card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USE [dbRent_blank]
        '''GO
        '''/****** Object:  Table [dbo].[tblWorkers]    Script Date: 07/17/2014 19:24:08 ******/
        '''SET ANSI_NULLS ON
        '''GO
        '''SET QUOTED_IDENTIFIER ON
        '''GO
        '''CREATE TABLE [dbo].[tblWorkers](
        '''	[WorkerID] [int] NOT NULL,
        '''	[WorkerName] [nvarchar](255) NULL,
        '''	[DC_Date] [datetime] NULL,
        '''	[Started_Date] [datetime] NULL,
        '''	[Email] [nvarchar](255) NULL,
        '''	[MobileNo] [nvarchar](255) NULL,
        '''	[PreferredContactMethod] [nvarchar](255) NULL,
        '''	[AdditionalInfo] [ntext] NULL,
        '''	[Status] [nvarchar](255) NULL,
        '''	[C [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property Schema() As String
            Get
                Return ResourceManager.GetString("Schema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property visa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("visa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
